version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "latest"

sphinx:
  configuration: docs/conf.py

formats: all

submodules:
  exclude: all

python:
  install:
    - requirements: docs/requirements.txt
