name: Build

on:
  workflow_call:
    inputs:
      publish:
        required: false
        type: boolean
        default: false

env:
  NODE_VERSION: 20
  JAVA_VERSION: 17

permissions:
  contents: read

jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.set-vars.outputs.app-version }}
      docker-tags: ${{ steps.set-vars.outputs.docker-tags }}
      snap-channel: ${{ steps.set-vars.outputs.snap-channel }}
      docs-url: ${{ steps.set-vars.outputs.docs-url }}
      vcs-ref: ${{ steps.set-vars.outputs.vcs-ref }}
      build-date: ${{ steps.set-vars.outputs.build-date }}
    steps:
      - name: Set variables
        id: set-vars
        run: |
          ref="${GITHUB_REF_NAME#v}"

          # set image name
          docker_image="elkozmon/zoonavigator"

          # is this a semver release?
          if [[ "${ref}" =~ ^[0-9]+(\.[0-9]+){2,3}$ ]];
          then
              app_version="${ref}"
              snap_channel="stable"
              docker_tags="${docker_image}:${ref},${docker_image}:latest"
              docs_url="https://zoonavigator.elkozmon.com/en/${ref}"
          else
              app_version="latest-${GITHUB_SHA::12}"
              snap_channel="beta"
              docker_tags="${docker_image}:unstable"
              docs_url="https://zoonavigator.elkozmon.com/en/latest"
          fi

          echo "app-version=${app_version}" >> "$GITHUB_OUTPUT"
          echo "docker-tags=${docker_tags}" >> "$GITHUB_OUTPUT"
          echo "snap-channel=${snap_channel}" >> "$GITHUB_OUTPUT"
          echo "docs-url=${docs_url}" >> "$GITHUB_OUTPUT"
          echo "vcs-ref=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          echo "build-date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$GITHUB_OUTPUT"

  build-docker:
    runs-on: ubuntu-latest
    needs:
      - setup-env
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ github.workspace }}/build/docker/Dockerfile
          push: false
          outputs: |
            type=docker,dest=docker-image-amd64.tar
            type=local,dest=out
          tags: ${{ needs.setup-env.outputs.docker-tags }}
          build-args: |
            APP_VERSION=${{ needs.setup-env.outputs.app-version }}
            DOCS_URL=${{ needs.setup-env.outputs.docs-url }}
            VCS_REF=${{ needs.setup-env.outputs.vcs-ref }}
            BUILD_DATE=${{ needs.setup-env.outputs.build-date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-amd64
          path: docker-image-amd64.tar

      - name: Package jars
        run: tar -cvzf jars.tar.gz -C out/app lib

      - name: Upload jars
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: jars.tar.gz

  build-snap:
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
    runs-on: ${{ matrix.architecture == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    needs:
      - setup-env
      - build-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download jars
        id: download-jars
        uses: actions/download-artifact@v4
        with:
          name: jars

      - name: Prepare Snap files
        run: |
          echo "${{ needs.setup-env.outputs.app-version }}" \
            > ${GITHUB_WORKSPACE}/build/snap/local/version

          tar \
            -xvf ${{ steps.download-jars.outputs.download-path }}/jars.tar.gz \
            -C ${GITHUB_WORKSPACE}/build/snap/local

      - name: Build Snap
        id: build-snap
        uses: snapcore/action-build@v1
        with:
          path: build/

      - name: Upload Snap
        uses: actions/upload-artifact@v4
        with:
          name: snap-${{ matrix.architecture }}
          path: ${{ steps.build-snap.outputs.snap }}

  test-e2e:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - docker
          - snap
        zookeeper:
          - 3.9
        architecture:
          - amd64
    runs-on: ubuntu-latest
    env:
      ZK_PORT: 2181
      ZN_PORT: 9000
    needs:
      - setup-env
      - build-docker
      - build-snap
    services:
      zookeeper:
        image: zookeeper:${{ matrix.zookeeper }}
        ports:
          - 2181:2181
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: e2e/package-lock.json

      - name: Install e2e dependencies
        working-directory: e2e
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: e2e
        run: npx playwright install --with-deps

      # Docker-specific steps
      - name: Download Docker image
        if: matrix.platform == 'docker'
        id: download-docker-image
        uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ matrix.architecture }}

      - name: Load Docker image
        if: matrix.platform == 'docker'
        run: |
          docker load < ${{ steps.download-docker-image.outputs.download-path }}/docker-image-${{ matrix.architecture }}.tar

      - name: Start ZooNavigator Docker container
        if: matrix.platform == 'docker'
        env:
          DOCKER_TAGS: ${{ needs.setup-env.outputs.docker-tags }}
        run: |
          docker run -d \
            --name zoonavigator-test \
            --network host \
            -e HTTP_PORT=${{ env.ZN_PORT }} \
            ${DOCKER_TAGS%%,*}

      # Snap-specific steps
      - name: Download Snap
        if: matrix.platform == 'snap'
        id: download-snap
        uses: actions/download-artifact@v4
        with:
          name: snap-${{ matrix.architecture }}

      - name: Install Snap daemon
        if: matrix.platform == 'snap'
        run: |
          sudo apt update
          sudo apt install -y snapd

      - name: Install ZooNavigator Snap
        if: matrix.platform == 'snap'
        run: |
          sudo snap install --dangerous ${{ steps.download-snap.outputs.download-path }}/zoonavigator_${{ needs.setup-env.outputs.app-version }}_${{ matrix.architecture }}.snap

      - name: Configure ZooNavigator Snap
        if: matrix.platform == 'snap'
        run: |
          sudo snap set zoonavigator zoonavigator.server.http.port=${{ env.ZN_PORT }}

      - name: Start ZooNavigator Snap
        if: matrix.platform == 'snap'
        run: |
          sudo snap start zoonavigator

      # Common steps
      - name: Wait for ZooNavigator to startup
        uses: emilioschepis/wait-for-endpoint@v1.0.4
        with:
          url: http://localhost:${{ env.ZN_PORT }}
          method: GET
          expected-status: 200
          timeout: 60000
          interval: 1000

      - name: Run e2e tests
        working-directory: e2e
        env:
          CI: true
          ZK_TEST_NODE: /test-${{ matrix.platform }}-${{ github.run_id }}
          ZK_CONNECTION_STRING: localhost:${{ env.ZK_PORT }}
          ZN_BASE_URL: http://localhost:${{ env.ZN_PORT }}
        run: npm test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.platform }}-${{ matrix.architecture }}
          path: e2e/playwright-report/
          retention-days: 7

  publish-docker:
    runs-on: ubuntu-latest
    if: inputs.publish
    needs:
      - setup-env
      - build-docker
      - test-e2e
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ github.workspace }}/build/docker/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: ${{ needs.setup-env.outputs.docker-tags }}
          build-args: |
            APP_VERSION=${{ needs.setup-env.outputs.app-version }}
            DOCS_URL=${{ needs.setup-env.outputs.docs-url }}
            VCS_REF=${{ needs.setup-env.outputs.vcs-ref }}
            BUILD_DATE=${{ needs.setup-env.outputs.build-date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  publish-snap:
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
    runs-on: ubuntu-latest
    if: inputs.publish
    needs:
      - setup-env
      - build-snap
      - test-e2e
    steps:
      - name: Download Snap
        id: download-snap
        uses: actions/download-artifact@v4
        with:
          name: snap-${{ matrix.architecture }}

      - name: Publish Snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_CREDENTIALS }}
        with:
          snap: ${{ steps.download-snap.outputs.download-path }}/zoonavigator_${{ needs.setup-env.outputs.app-version }}_${{ matrix.architecture }}.snap
          release: ${{ needs.setup-env.outputs.snap-channel }}

  cleanup:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - build-docker
      - build-snap
      - test-e2e
      - publish-docker
      - publish-snap
    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            jars
            docker-image-amd64
            snap-amd64
            snap-arm64
